# Generated by Django 4.1.7 on 2023-03-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0002_cart_user_orderid_order_cart_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderid',
            name='oderId',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
