# Generated by Django 4.1.7 on 2023-03-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0004_rename_oderid_orderid_datetime_remove_cart_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default='dd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='phoneNum',
            field=models.CharField(default='3355', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='user@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(default='anc.png', upload_to='users/profilepic'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='orderid',
            unique_together={('uid', 'dateTime')},
        ),
    ]
